# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagearticle',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imagearticle',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
