# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0011_dietdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dietdata',
            options={'ordering': ('created', 'author', 'height', 'weight', 'step', 'calorie')},
        ),
        migrations.RenameField(
            model_name='dietdata',
            old_name='calrorie',
            new_name='calorie',
        ),
    ]
