# Generated by Django 2.0.dev20170314235856 on 2017-06-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0012_auto_20170610_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=30)),
                ('music', models.FileField(max_length=255, upload_to='')),
            ],
        ),
    ]
