# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0015_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='content',
        ),
        migrations.AddField(
            model_name='route',
            name='end_address',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_address',
            field=models.TextField(default='b'),
            preserve_default=False,
        ),
    ]
